name: daily-umami-report

on:
  schedule:
    - cron: '30 17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  umamiReportJob:
    name: daily umami report
    runs-on: ubuntu-latest

    outputs:
      umami_page_views: ${{ steps.umamiReportStep.outputs.pageViews }}
      umami_report_file: ${{ steps.umamiReportStep.outputs.umamiReportFile }}
#      umami_report: ${{ steps.umamiReport.outputs.umamiReport }}
#      umami_one_line_report: ${{ steps.umamiReport.outputs.umamiOneLineReport }}
    steps:
      - name: Create Daily Umami report
        id: umamiReportStep
        uses: boly38/action-umami-report@main
        with:
          umami-server: https://${{secrets.UMAMI_SERVER}}
          umami-user: ${{secrets.UMAMI_USERNAME}}
          umami-password: ${{secrets.UMAMI_PASSWORD}}
          umami-site-domain: ${{secrets.UMAMI_SITE_DOMAIN}}
          umami-report-file: 'umamiReport.txt'
        env:
          UMAMI_CLIENT_TIMEOUT_MS: 5000

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
            host: smtp.resend.com
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: isaac
            from: ${{secrets.MAIL_ADDRESS}}
            to: isaac.almanza19@gmail.com
            subject: umami report
            body: your messages.
      # Optional content type (defaults to text/plain)
            contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
            attachments: '[{"path": "${{ steps.umamiReportStep.outputs.umamiReportFile }}" }]'

      - name: Have a look at !secret results from next step using outputs
        run: |
          echo "${{ steps.umamiReportStep.outputs.umamiReportFile }}"
          ls -la "${{ steps.umamiReportStep.outputs.umamiReportFile }}"

  nextJob:
    needs: umamiReportJob
    name: github action next job
    runs-on: ubuntu-latest
    steps:
      - name: print var
        run: |
          echo "FROM umamiReport outputs: ${{ needs.umamiReportJob.outputs.umami_report_file }} and ${{ needs.umamiReportJob.outputs.umami_page_views }} pageviews "